
name: Current Branch Status

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Base Docker container with Flyway
        run: |
          sudo docker-compose up -d db
          sleep 5
          sudo docker-compose run flyway

